version: "3"
services:

#  influxdb:
#    image:  influxdb:1.5.3
#    ports:
#      - "8086:8086"
#      - "8083:8083"
#      - "2003:2003"
#    environment:
#      - INFLUXDB_ADMIN_ENABLED=true
#    volumes:
#      - "./data:/var/lib/influxdb"
#    network_mode: host

#  grafana:
#    image: grafana/grafana
#    ports:
#      - "3000:3000"
#    environment:
#      - GF_INSTALL_PLUGINS=grafana-kairosdb-datasource
#    depends_on:
#      - influxdb
#    network_mode: host
  influxdb:
    image: influxdb:1.5.3
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    env_file:
      - 'env.influxdb'
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/influxdb/data
      - ./data:/var/lib/influxdb
    network_mode: host

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - 'env.grafana'
    network_mode: host
